import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l ts ./src/types`.

export enum PayrollBloodType {
    AP = "Ap",
    AN = "An",
    BP = "Bp",
    BN = "Bn",
    A_BP = "ABp",
    A_BN = "ABn",
    OP = "Op",
    ON = "On"
}

export enum PayrollGender {
    MALE = "male",
    FEMALE = "female",
    OTHER = "other"
}

export enum PayrollMaritalStatus {
    SINGLE = "single",
    MARRIED = "married",
    DIVORCED = "divorced",
    WIDOWED = "widowed",
    FREE_UNION = "free union"
}

export enum PayrollBankAccountType {
    SAVINGS = "savings",
    CHECKING = "checking"
}

export enum PayrollEducationEducationLevel {
    PRIMARY = "primary",
    SECONDARY = "secondary",
    POST_SECONDARY = "post-secondary",
    TERTIARY = "tertiary",
    OTHER = "other"
}

export enum PayrollFamilyRelationship {
    PARENT = "parent",
    SPOUSE = "spouse",
    CHILD = "child",
    OTHER = "other"
}

export enum ClientsTaxpayerType {
    PERSON_NON_OBLIGATED = "person-non-obligated",
    PERSON_OBLIGATED = "person-obligated",
    PUBLIC_SOCIETY = "public-society",
    PRIVATE_SOCIETY = "private-society"
}

export enum OrdersStatus {
    PENDING = "pending",
    PAID = "paid",
    OTHER = "other",
    CANCELED = "canceled"
}

export enum WithholdingsType {
    TAX = "tax",
    SOURCE = "source"
}

export enum InvoicesStatus {
    PENDING = "pending",
    PAID = "paid"
}

export enum InvoicesPaymentType {
    CASH = "cash",
    TRANSFER = "transfer",
    EXCHANGE = "exchange",
    CARD = "card"
}

export type CostCenters = Models.Row & {
    name: string;
    deletedAt: string | null;
}

export type Schedules = Models.Row & {
    name: string;
    morningArrival: string;
    morningDeparture: string;
    afternoonArrival: string;
    afternoonDeparture: string;
    waitMinutes: number;
    graceMinutes: number;
    deletedAt: string | null;
}

export type Payroll = Models.Row & {
    idNumber: string;
    photo: string | null;
    birthDate: string;
    birthPlace: string;
    nationality: string;
    nativeLanguage: string;
    firstName: string;
    lastName: string;
    address: string;
    sector: string;
    homeVisit: boolean;
    visitDate: string | null;
    phone: string | null;
    mobile: string;
    email: string;
    bloodType: PayrollBloodType;
    medicalConditions: string | null;
    allergies: string | null;
    emergencyContactName: string | null;
    emergencyContactAddress: string | null;
    emergencyContactMobile: string | null;
    emergencyContactOffice: string | null;
    gender: PayrollGender;
    maritalStatus: PayrollMaritalStatus;
    childrenCount: number | null;
    hireDate: string;
    terminationDate: string | null;
    position: string;
    costCenterId: CostCenters;
    socialSecurityEnrollment: string | null;
    socialSecurityEmployerPaid: boolean;
    salary: number;
    monthlySettlement: boolean;
    bankId: number;
    bankAccountType: PayrollBankAccountType;
    bankAccountNumber: string;
    notes: string | null;
    active: boolean;
    scheduleId: Schedules;
    canOvertime: boolean;
    deletedAt: string | null;
}

export type Credentials = Models.Row & {
    account: string;
    username: string;
    password: string;
    hint: string | null;
    url: string | null;
    deletedAt: string | null;
}

export type PayrollEducation = Models.Row & {
    payrollId: Payroll;
    educationLevel: PayrollEducationEducationLevel;
    institutionName: string;
    startDate: string;
    endDate: string;
    degree: string;
    deletedAt: string | null;
}

export type PayrollFamily = Models.Row & {
    payrollId: Payroll;
    relationship: PayrollFamilyRelationship;
    name: string;
    birthDate: string;
    occupation: string | null;
    phone: string | null;
    mobile: string | null;
    deletedAt: string | null;
}

export type PayrollReferences = Models.Row & {
    payrollId: Payroll;
    referenceType: boolean;
    companyName: string | null;
    contactName: string;
    phone: string;
    relationship: string;
    startDate: string | null;
    endDate: string | null;
    position: string | null;
    separationReason: string | null;
    deletedAt: string | null;
}

export type PayrollDocuments = Models.Row & {
    payrollId: Payroll;
    entryNotice: boolean;
    workContract: boolean;
    jobApplication: boolean;
    resume: boolean;
    idCard: boolean;
    voterCard: boolean;
    policeRecord: boolean;
    militaryCard: boolean;
    elementaryCertificate: boolean;
    highSchoolCertificate: boolean;
    universityCertificate: boolean;
    otherCertificate: boolean;
    employmentReferences: boolean;
    personalReferences: boolean;
    medicalCertificate: boolean;
    exitNotice: boolean;
    settlementAct: boolean;
    settlementPaymentReceipt: boolean;
    deletedAt: string | null;
}

export type PayrollEquipment = Models.Row & {
    payrollId: Payroll;
    deliveryDate: string;
    equipmentId: Equipment;
    deletedAt: string | null;
}

export type Equipment = Models.Row & {
    name: string;
    active: boolean;
    deletedAt: string | null;
}

export type Modules = Models.Row & {
    name: string;
    isMain: boolean;
    deletedAt: string | null;
}

export type Profiles = Models.Row & {
    name: string;
    description: string;
    active: boolean;
    deletedAt: string | null;
}

export type Roles = Models.Row & {
    name: string;
    deletedAt: string | null;
    level: number;
}

export type ProfileModules = Models.Row & {
    profileId: Profiles;
    moduleId: Modules;
    roleId: Roles;
    deletedAt: string | null;
}

export type Users = Models.Row & {
    authId: string;
    idNumber: string;
    active: boolean;
    reserveOrder: boolean;
    bookAccess: boolean;
    profitAccess: boolean;
    isSuperAdmin: boolean;
    deletedAt: string | null;
    profileId: Profiles;
    firstName: string;
    lastName: string;
}

export type Attendance = Models.Row & {
    userId: Users;
    date: string;
    morningArrival: string;
    morningDeparture: string | null;
    afternoonArrival: string | null;
    afternoonDeparture: string | null;
    totalHours: string | null;
    overtimeHours: string | null;
    deletedAt: string | null;
}

export type CompanyDetails = Models.Row & {
    name: string;
    legalRepresentative: string;
    ruc: string;
    city: string;
    address: string;
    phone: string;
    mobile: string;
    website: string;
    email: string;
    orderStart: number;
    cloudStorage: string | null;
    mailConfig: string | null;
    deletedAt: string | null;
}

export type Companies = Models.Row & {
    name: string;
    ruc: string;
    deletedAt: string | null;
    activity: string;
}

export type Contacts = Models.Row & {
    title: string | null;
    firstName: string;
    lastName: string;
    position: string | null;
    address: string | null;
    sector: string | null;
    phone: string | null;
    mobile: string;
    extension: number | null;
    email: string | null;
    website: string | null;
    deletedAt: string | null;
    companyId: Companies;
}

export type Clients = Models.Row & {
    contactId: Contacts;
    followUp: boolean;
    taxpayerType: ClientsTaxpayerType;
    deletedAt: string | null;
    companyId: Companies;
}

export type UserClients = Models.Row & {
    userId: Users;
    clientId: Clients;
    deletedAt: string | null;
}

export type Orders = Models.Row & {
    number: number;
    userId: Users;
    clientId: Clients;
    startDate: string;
    endDate: string;
    collectionDate: string | null;
    priority: boolean;
    status: OrdersStatus;
    quotedPrice: number;
    description: string;
    paperType: string | null;
    quantity: number;
    cutHeight: number;
    cutWidth: number;
    numberingStart: number;
    numberingEnd: number;
    materialTotal: number;
    orderTotal: number;
    paymentAmount: number;
    balance: number;
    notes: string | null;
    deletedAt: string | null;
    processes: OrderProcesses[];
}

export type OrderPayments = Models.Row & {
    orderId: Orders;
    date: string;
    userId: Users;
    method: string;
    amount: number;
    deletedAt: string | null;
}

export type Areas = Models.Row & {
    name: string;
    sortOrder: number;
    deletedAt: string | null;
}

export type Suppliers = Models.Row & {
    name: string;
    phone: string;
    address: string;
    deletedAt: string | null;
}

export type Categories = Models.Row & {
    name: string;
    deletedAt: string | null;
}

export type OrderProcesses = Models.Row & {
    orderId: Orders;
    processId: Processes;
    frontColors: number;
    backColors: number;
    thousands: number;
    unitPrice: number;
    total: number;
    done: boolean;
    deletedAt: string | null;
}

export type Processes = Models.Row & {
    areaId: Areas;
    name: string;
    goal: number;
    machineTime: string | null;
    operatorTime: string | null;
    internal: boolean;
    followUp: boolean;
    deletedAt: string | null;
    parentId: string | null;
}

export type UserProcesses = Models.Row & {
    userId: Users;
    processId: Processes;
    deletedAt: string | null;
}

export type Inks = Models.Row & {
    color: string;
    deletedAt: string | null;
}

export type OrderInks = Models.Row & {
    orderId: Orders;
    inkId: Inks;
    side: boolean;
    deletedAt: string | null;
}

export type Materials = Models.Row & {
    name: string;
    categoryId: Categories;
    hasColor: boolean;
    height: number | null;
    width: number | null;
    price: number | null;
    hasUv: boolean;
    hasLaminated: boolean;
    deletedAt: string | null;
}

export type OrderMaterials = Models.Row & {
    orderId: Orders;
    materialId: Materials;
    quantity: number;
    cutHeight: number;
    cutWidth: number;
    sizes: number;
    supplierId: Suppliers;
    invoiceNumber: number | null;
    total: number;
    deletedAt: string | null;
}

export type Taxes = Models.Row & {
    percentage: number;
    active: boolean;
    deletedAt: string | null;
}

export type BillingCompanies = Models.Row & {
    email: string;
    validFrom: string;
    validTo: string;
    startNumber: number;
    taxId: Taxes;
    businessName: string;
    legalRepresentative: string;
    address: string;
    city: string;
    phone: string;
    mobile: string | null;
    ruc: string;
    sriKey: string | null;
    sriSignatureKey: string | null;
    cashierCode: string;
    taxWithholdingId: Withholdings;
    sourceWithholdingId: Withholdings;
    canPrint: boolean;
    logo: string | null;
    active: boolean;
    deletedAt: string | null;
}

export type Withholdings = Models.Row & {
    percentage: number;
    description: string;
    active: boolean;
    deletedAt: string | null;
    type: WithholdingsType;
}

export type Invoices = Models.Row & {
    userId: Users;
    invoiceNumber: number;
    billingCompanyId: BillingCompanies;
    clientId: Clients;
    issueDate: string;
    dueDate: string;
    type: boolean;
    status: InvoicesStatus;
    paymentDate: string | null;
    paymentType: InvoicesPaymentType;
    subtotal: number;
    discountPercentage: number;
    discount: number;
    tax: number;
    taxExempt: number;
    total: number;
    withholdingId: Withholdings;
    withholding: number;
    sourceWithholdingId: Withholdings;
    sourceWithholding: number;
    totalPayable: number;
    notes: string | null;
    deletedAt: string | null;
}

export type InvoiceWorkOrders = Models.Row & {
    invoiceId: Invoices;
    orderId: Orders;
    deletedAt: string | null;
}

export type AccountingBooks = Models.Row & {
    name: string;
    deletedAt: string | null;
}

export type BookReferences = Models.Row & {
    reference: string;
    description: string;
    deletedAt: string | null;
}

export type UserBook = Models.Row & {
    userId: Users;
    bookId: AccountingBooks;
    deletedAt: string | null;
}

export type BankAccounts = Models.Row & {
    name: string;
    accountNumber: string;
    deletedAt: string | null;
}

export type BookTransactions = Models.Row & {
    userId: Users;
    bookId: AccountingBooks;
    bookReferenceId: BookReferences;
    transactionDate: string;
    beneficiary: string;
    idNumber: string | null;
    detail: string;
    transactionType: boolean;
    income: number | null;
    expense: number | null;
    bankId: BankAccounts;
    accountNumber: string | null;
    checkNumber: string | null;
    deletedAt: string | null;
}

export type InvoiceProducts = Models.Row & {
    invoiceId: Invoices;
    quantity: number;
    detail: string;
    taxId: Taxes;
    unitPrice: number;
    subtotal: number;
    deletedAt: string | null;
}

export type Templates = Models.Row & {
    name: string;
    content: string;
    logo: string | null;
    deletedAt: string | null;
}

export type ProductionResets = Models.Row & {
    resetTimestamp: string;
    userId: Users;
    deletedAt: string | null;
}

export type Crm = Models.Row & {
    scheduled: string;
    activityId: Activities;
    assignedId: Users;
    contactId: Contacts;
    active: boolean;
    source: string | null;
    campaign: string | null;
    note: string | null;
    deletedAt: string | null;
}

export type Activities = Models.Row & {
    name: string;
    goal: number | null;
    templateId: Templates;
    canEvaluate: boolean;
    followUp: boolean;
    deletedAt: string | null;
}

export type Comments = Models.Row & {
    userId: Users;
    contactId: Contacts;
    comment: string;
    deletedAt: string | null;
    parentId: string | null;
}

export type Notifications = Models.Row & {
    userId: Users;
    type: string;
    content: string;
    readAt: string | null;
}

export type ProductCategories = Models.Row & {
    name: string;
    parentId: string | null;
}

export type Products = Models.Row & {
    categoryId: ProductCategories;
    name: string;
    description: string;
}
