export const DATABASE_ID =
	import.meta.env.VITE_APPWRITE_DATABASE_ID || "public";

export enum TABLES {
	// Accounting
	ACCOUNTING_BOOKS = "accounting-books",
	BANK_ACCOUNTS = "bank-accounts",
	BILLING_COMPANIES = "billing-companies",
	BOOK_REFERENCES = "book-references",
	BOOK_TRANSACTIONS = "book-transactions",
	COST_CENTERS = "cost-centers",
	INVOICE_ORDERS = "invoice-orders",
	INVOICE_PRODUCTS = "invoice-products",
	INVOICES = "invoices",
	TAXES = "taxes",
	WITHHOLDINGS = "withholdings",
	// Employees
	ATTENDANCE = "attendance",
	EQUIPMENT = "equipment",
	PAYROLL = "payroll",
	PAYROLL_DOCUMENTS = "payroll-documents",
	PAYROLL_EDUCATION = "payroll-education",
	PAYROLL_EQUIPMENT = "payroll-equipment",
	PAYROLL_FAMILY = "payroll-family",
	PAYROLL_REFERENCES = "payroll-references",
	SCHEDULES = "schedules",
	// Production
	AREAS = "areas",
	CATEGORIES = "categories",
	INKS = "inks",
	MATERIAL_REQUESTS = "material-requests",
	MATERIALS = "materials",
	ORDER_INKS = "order-inks",
	ORDER_PROCESSES = "order-processes",
	ORDERS = "orders",
	PAYMENTS = "payments",
	PROCESSES = "processes",
	PRODUCTION_RESETS = "production-resets",
	SUPPLIERS = "suppliers",
	CLIENT_FOLLOWERS = "client-followers",
	// Sales
	ACTIVITIES = "activities",
	CLIENT_COMPANIES = "client-companies",
	CLIENTS = "clients",
	COMMENTS = "comments",
	CONTACTS = "contacts",
	CRM = "crm",
	TEMPLATES = "templates",
	// Store
	PRODUCT_CATEGORIES = "product-categories",
	PRODUCTS = "products",
	// System
	COMPANY_DETAILS = "company-details",
	CREDENTIALS = "credentials",
	NOTIFICATIONS = "notifications",
	// Users
	MODULES = "modules",
	PROFILE_MODULES = "profile-modules",
	PROFILES = "profiles",
	ROLES = "roles",
	USER_BOOK = "user-book",
	USER_CLIENTS = "user-clients",
	USER_PROCESSES = "user-processes",
	USERS = "users",
}
